### ISSUE TITLE
[BUG]: Stick overload

### ISSUE THREAD

**Issue by dirixmjm** [plugwise/python-plugwise-usb#25]
### Describe the bug.

There still is some kind of race condition which leads to overloading the stick with messages. At some point the log starts showing Drops. I have tried increasing the time out and setting to 25 and  the repeat to 1 to reduce the message rate increase, but still it starts dropping messages.

Once the stick is overloaded, a simple restart of HAS does not change the condition because the stick keeps trying to work through all sent messages. Therefore a power cycle of the stick is needed as well.

The problem starts to appear as early as 10 minutes after starting HAS with original time out and repeat settings. The attached log however uses 25 secs time out and repeat to 1.

### Expected behavior

No race condition / limit on number of messages transmitted.

### What version of Home Assistant Core has the issue?

2023.4.2

### What type of installation are you running?

Home Assistant Core

### How and which version of the integration do you have installed?

Home Assistant Core

### What firmware version is your Plugwise product at?

0.40.1

### Home Assistant Logging (optional)

[home-assistant_plugwise_usb_2023-05-15T15-24-26.146Z.log](https://github.com/plugwise/python-plugwise-usb/files/11485194/home-assistant_plugwise_usb_2023-05-15T15-24-26.146Z.log)

### Diagnostics information

Python 3.11

**Comment by dirixmjm** [comment]
To be honest I have little experience with Python programming, however I did develop the plugwise usb stick code for Pike (see attached). In that code I rate limited (even though the code works asynchronously) the commands to the stick to 1 at a time. Most likely the stick can handle more commands simultaneously, but probably a rate limit needs to be implemented nonetheless.

I am also wondering about some of the commands being sent, if a plug responds to a power usage request, do we really need to sent out a ping message? As I understand it, ping messages are for resetting the mesh network and possibly flood the network. It would be my suggestion to sent ping messages only if a plug fails to respond and also rate limit those.
[Public_IO_PlugWise.zip](https://github.com/plugwise/python-plugwise-usb/files/11485606/Public_IO_PlugWise.zip)

**Comment by CoMPaTech** [comment]
@brefra can you have a look for @dirixmjm?

**Comment by dirixmjm** [comment]
@CoMPaTech @brefra  I just generated a pull request that I think fixes a big portion of my problem. The network has quiet down a lot.
